# Generated by Django 5.2.2 on 2025-06-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='booking',
            name='session',
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.CheckConstraint(condition=models.Q(('available_slots__gte', 0)), name='available_slots_non_negative'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
