# Generated by Django 5.2.2 on 2025-06-07 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('classes', '0002_alter_booking_unique_together_remove_booking_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='classes.classsession')),
            ],
            options={
                'ordering': ['-booking_time'],
                'unique_together': {('session', 'client_email')},
            },
        ),
        migrations.DeleteModel(
            name='ClassType',
        ),
    ]
