# Generated by Django 5.2.2 on 2025-06-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_delete_classtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booked_at']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='booked_at',
        ),
    ]
